[package]
# Package Information
name = oposs_isam_gpon
title = OPOSS Nokia ISAM GPON
author = Tobias Oetiker <tobi@oetiker.ch>
description = This check monitors Nokia ISAM GPON equipment via SNMP.

    It tracks line card availability and GPON port status including
    SFP optics (power, voltage, temperature, bias current) and
    traffic statistics (bytes, utilization, active ONTs).

# CheckMK Compatibility
version.min_required = 2.3.0p1
version.packaged = 2.3.0p34

# Optional
download_url = https://github.com/oposs/cmk-oposs_isam_gpon
version.usable_until =

# Build Options
validate_python = true
